<table width="100%" cellpadding="0" cellspacing="0">
	
	<tr>
		<td>
		
			<div class="inputBox">
				<table width="548" cellpadding="0" cellspacing="0">
					<!-- =================================================================================================================== -->
					<!-- ============== FORM utilizado para persistir um perfil:  salvar e editar um pefil ================================= -->
					<!-- =================================================================================================================== -->
					<form action="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php if($this->escape($this->form->getId()) != null){echo DEFAULT_EDIT_ACTION;}else{echo DEFAULT_ADD_ACTION;}?>" method="post">
						<tr>
							<td colspan="4">
								<h1 class="title"><?php echo $this->controller->profile->title->registerProfile;?></h1>
							</td>
						</tr>
						<tr>
							<td class="label" width="25%">
								<?php echo $this->controller->profile->text->profileName;?>:
							</td>
							
							<td width="39%">
								<input type="hidden" value="<?php echo $this->escape($this->form->getId());?>" name="<?php echo $this->form->id();?>"/>
								<input class="middleInput" type="text" maxlength="90" name="<?php echo ProfileForm::profileName();?>"  value="<?php echo $this->escape($this->form->getProfileName());?>" />
							</td>
							
							<td width="20%">
								<div class="inputs">
									<select class="smallInput" name="<?php echo $this->form->status();?>">
										<option value="<?php echo Constants::ENABLE;?>" <?php if($this->form->getStatus() == Constants::ENABLE) echo "selected";?>><?php echo $this->labels->text->enable;?></option>
										<option value="<?php echo Constants::DISABLE;?>" <?php if($this->form->getStatus() == Constants::DISABLE) echo "selected";?>><?php echo $this->labels->text->disable;?></option>
									</select>
								</div>
							</td>
							
							<td>
								<input class="button" style="margin: 0;" type="submit" value="<?php echo $this->labels->button->save;?>"/>
							</td>
						</tr>
						
						<tr>
							<td colspan="4">
								<?php printErrorsByField($this->form->profileName(), $this->errorMessages);?>
								<?php printErrorsByField($this->form->status(), $this->errorMessages);?>
							</td>
						</tr>
					</form>
					<!-- ================================================================================================================== -->
					<!-- ======================================================== fim do FORM ============================================= -->
					<!-- ================================================================================================================== -->
					
				</table>
			</div>
		</td>
	</tr>

	<tr>
		<td>
			<!-- =================================================================================================================== -->
			<!-- ===================== FORM utilizado para carregar um ou mais perfis para ser excluído ============================ -->
			<!-- ========================= FORM utilizado para carregar um perfil para ser editado ================================= -->
			<!-- =================================================================================================================== -->
			<form id="<?php echo PROFILE_FORM;?>" method="post">
			
				<div class="inputBox">
					<table width="548" cellpadding="0" cellspacing="0">
					
						<tr>
							<td colspan="2">
								<h1 class="title"><?php echo $this->controller->profile->title->manage;?></h1>
							</td>
						</tr>
						
						<tr>
							<td width="27%" class="label">
								<?php echo $this->controller->profile->text->listProfile;?>:
							</td>
							<td width="73%" colspan="2">
								<select id="typeProfile" name="<?php echo $this->form->id();?>[]" size="10" multiple>
									<?php 
										foreach($this->profiles as $profile)
										{
											echo "<option value='".$profile->{AUTH_ID_PROFILE}."' title='".$profile->{AUTH_PROFILE}."'>".$profile->{AUTH_PROFILE};
											if($profile->{AUTH_STATUS} == Constants::DISABLE)
												echo "&nbsp;*&nbsp;".$this->labels->text->disable."&nbsp;*";
											echo "</option>";
										}
									?>
								</select>
							</td>
						</tr>
						
						<tr>
							<td colspan="2">
								<input class="button" type="submit" value="<?php echo $this->labels->button->edit;?>" 
								onClick="javascript: return reportMultipleSelected('<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_VIEW_ACTION;?>',this.form, 'typeProfile');">
								<input class="button" style="margin-left: 5px;" type="submit" value="<?php echo $this->labels->button->disable;?>" 
								onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_CONFIRM_ACTION;?>',this.form);">
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->id(), $this->errorMessages);?></td>
						</tr>
						
					</table>
				</div>
				
			</form>
			<!-- =================================================================================================================== -->
			<!-- ======================================================== fim do FORM ============================================== -->
			<!-- =================================================================================================================== -->
		</td>
	</tr>
</table>
