<?php
/*
 * 
 * Created on 19/02/2008 
 * S2it Solutions by Fabricio Meireles Monteiro
 * 
 */
?>
 
<?php echo $this->render('header/header.phtml');?>

	
	<table width="570" cellpadding="0" cellpadding="0">
		<?php 
			if(!$this->errorMessages)
			{
				echo $this->render('profile/previewDrop.phtml');
			}
			else
			{
				echo $this->render('profile/invalidParam.phtml');
			}
		?>
	</table>

	
<?php echo $this->render('footer/footer.phtml');?>
 

