<tr>
	<td>				
		<h1 class="title" style="margin-top:33px;"><?php echo ($this->labels->confirm->disable->title);?></h1>
	</td>
</tr>

<tr>
	<td width="100%" align="center" cellpadding="0" cellspacing="0">
		<div class="inputBox">
			<table width="548" cellpadding="0" cellspacing="0">
				<tr>
					<td>
						<!-- =================================================================================================================== -->
						<!-- =================================== FORM utilizado para excluir um ou mais perfil ================================= -->
						<!-- =================================================================================================================== -->
						<form action="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
							<p style="margin-top: 10px;">
								<?php echo $this->labels->confirm->disable->text;?>&nbsp;?<br>
								<?php 
									foreach($this->objectProfiles as $profile)
									{
										echo "<br>".$this->controller->profile->text->profileName.":&nbsp;";
										echo "<input type='hidden' name='".$this->form->id()."[]' value='".$profile->{AUTH_ID_PROFILE}."'/>";
										echo "<b>". $profile->{AUTH_PROFILE}."</b><br>";
									}
								?>
							</p>
							<div>
								<input class="button" type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->yes;?>" />
								<input class="button" style="margin-left: 5px;" type="button" onClick="document.location='<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'" value="<?php echo $this->labels->confirm->button->cancel;?>" />
							</div>
						</form>	
						<!-- =================================================================================================================== -->
						<!-- ================================================ fim do FORM ====================================================== -->
						<!-- =================================================================================================================== -->		
					</td>
				</tr>
			</table>
		</div>
	</td>
</tr>
