<?php $show = Zend_Registry::get(CONFIG)->container->education;?>
<script type="text/javascript">	
	$('#imgFakeHide').hide();
	<?php if($show):?>
		$().ajaxSend(function(){$('#loading1').show();});		
		$.post('<?php echo $this->baseUrl;?><?php echo EDUCATION_CONTROLLER;?>/<?php echo DEFAULT_CONTAINER_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>', function(data){ $('#education').append(data);$('#loading1').hide();});
	<?php else:?>
		function showEdu()
		{
			$('#maxEducation').hide();
			$('#mainEducation').show();
			$().ajaxSend(function(){$('#loading1').show(); $('#imgHide').hide();$('#imgFakeHide').show();$('#tableHide').hide();$('#tableFakeHide').show();});		
			$.post('<?php echo $this->baseUrl;?><?php echo EDUCATION_CONTROLLER;?>/<?php echo DEFAULT_CONTAINER_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>', 
				function(data)
				{ 
					if(data.search(/<?php echo $this->labels->login->title;?>/i) != -1)
					{
						window.location.reload();
					}
					else
					{
						$('#education').append(data);
						$('#loading1').hide();
						$('#imgFakeHide').hide();
						$('#imgHide').show();
						$('#tableFakeHide').hide();
						$('#tableHide').show();
					}
				}
			);
		}
		
		function hideEdu()
		{
			$('#education').empty();
			$('#maxEducation').show();			
			$('#mainEducation').hide();
		}
	<?php endif;?>
	
</script>

<?php if(!$show):?>
<!-- Antigo --
<div id="maxEducation" class="education">
	<table class="education" width="100%">
		<tr>
			<td>
				<table width="100%" class="tableContainer" onClick="showEdu()">
					<tr>
						<td width="10%" class="fontContainer">
							<img id="imgShow" src="<?php echo $this->baseUrl;?>/public/images/show.png" title="<?php echo $this->labels->title->show;?>"/>
						</td>				
						<td width="90%" class="fontContainer">
							<b><?php echo $this->labels->title->education;?></b>
						</td>
					</tr>
				</table>				
			</td>
		</tr>
	</table>
</div>

-->

<div id="maxEducation">
	<div class="container containerDesatived" onClick="showEdu()">
		<div class="title">
			<span><?php echo $this->labels->title->education;?></span>
		</div>
		<div class="borderBottom"></div>	
	</div>
</div>

<?php endif;?>

<!-- Antigo --
<div id="mainEducation" <?php if(!$show):?>style="display: none;" <?php endif;?>>
	<table class="education" width="100%">
		<tr>
			<td class="container">
				
				<?php if(!$show):?>
					<table width="100%" class="tableContainer" id="tableHide" onClick="hideEdu()">
						<tr>
							<td width="10%" class="fontContainer">
								<img id="imgHide" src="<?php echo $this->baseUrl;?>/public/images/hide.png" title="<?php echo $this->labels->title->hide;?>"/>
								<img id="imgFakeHide" src="<?php echo $this->baseUrl;?>/public/images/hide.png" title="<?php echo $this->labels->title->hide;?>"/>
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->education;?></b>
							</td>
						</tr>
					</table>
					<table width="100%" class="tableContainer" id="tableFakeHide">
						<tr>
							<td width="10%" class="fontContainer">
								<img id="imgHide" src="<?php echo $this->baseUrl;?>/public/images/hide.png"  title="<?php echo $this->labels->title->hide;?>"/>								
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->education;?></b>
							</td>
						</tr>
					</table>
				<?php else:?>
					<table width="100%" class="tableContainer">
						<tr>
							<td width="10%" class="fontContainer">								
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->education;?></b>
							</td>
						</tr>
					</table>
				<?php endif;?>
				<p>							
				<div id="loading1">	<center><img src="<?php echo $this->baseUrl;?>/public/images/loading.gif"/></center>	</div>			
				<div id="education"></div>							
			</td>
		</tr>
	</table>
</div>
-->

<div id="mainEducation" <?php if(!$show):?>style="display: none;"<?php endif;?>>
	<div class="container">
		<?php if(!$show):?>
			<div class="containerFake" id="tableHide" onClick="hideEdu()">
				<div class="title">
					<span><?php echo $this->labels->title->education;?></span>
				</div>						
			</div>
			
			<div class="containerFake" id="tableFakeHide">
				<div class="title">
					<span><?php echo $this->labels->title->education;?></span>
				</div>
				<div id="loading1" class="loading"></div>
			</div>
			
		<?php else:?>
			<div class="container">
				<div class="textTitle">
					<?php echo $this->labels->title->education;?>
				</div>
			</div>
		<?php endif;?>				
			<div id="education"></div>
			<div class="borderBottom"></div>				
	</div>		
</div>

