<form action="<?php echo $this->baseUrl;?><?php echo ATTENDANCE_CONTROLLER;?>/<?php echo ASSISTANCE_ACTION;?>" method="post">
	<input type="hidden" name="<?php if($this->form)echo $this->form->programType();?>" value="<?php if($this->form)echo $this->form->getProgramType();?>"/>
	<input type="hidden" name="<?php if($this->form)echo $this->form->personId();?>" value="<?php if($this->form)echo $this->form->getPersonId();?>"/>
	<?php printErrorsByField($this->form->programType(), $this->errorMessages);?>
	<?php printErrorsByField($this->form->personId(), $this->errorMessages);?>
	<table width="100%" cellpadding="0" cellspacing="0">
	
		<tr>
			<td colspan="2">
				<h1 class="left"><?php echo $this->controller->attendance->text->general;?></h1>
			</td>
		</tr>
		
		<tr>
			<td colspan="2">
				<?php echo $this->helpcontroller->text2?>
			</td>
		</tr>
		
		<tr>
			<td width="40%" class="label">
				<?php echo $this->controller->attendance->text->previsionEndDate;?>
			</td>
			<td>
				<input class="smallInput" type="text" maxlength="10" name="<?php echo $this->form->endDate();?>" value="<?php if($this->form)echo $this->form->getEndDate();?>">
			</td>
		</tr>
		
		<tr>
			<td>&nbsp;</td>
			<td><?php echo $this->controller->attendance->text->dateFormat;?></td>
		</tr>
		
		<tr>
			<td colspan="2"><?php printErrorsByField($this->form->endDate(), $this->errorMessages);?></td>
		</tr>
		
		<tr>
			<td class="label">
				<?php echo $this->controller->attendance->text->confidential;?>
			</td>
			<td>
				<div class="radioCenter">
					<input type="radio" name="<?php echo $this->form->confidentiality();?>" value="<?php echo Constants::CONFIDENTIALITY_ENTITY;?>">&nbsp;<?php echo $this->labels->button->yes;?>
					<input type="radio" name="<?php echo $this->form->confidentiality();?>" value="<?php echo Constants::CONFIDENTIALITY_PUBLIC;?>" checked >&nbsp;<?php echo $this->labels->button->not;?>
				</div>
			</td>
		</tr>

		<tr>
			<td colspan="2">
				<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>"/>
				<input class="button" style="margin-left: 5px;" type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?>
				<?php echo ATTENDANCE_CONTROLLER;?>/<?php echo DEFAULT_ATTENDANCE_ACTION .'/'.$this->form->personId().'/'.$this->form->getPersonId();?>'">
			</td>
		</tr>
	</table>
</form>