<?php $case = false;?>
<?php $show = Zend_Registry::get(CONFIG)->container->lastattendance;?>
<?php if(!$show):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<?php $random = Zend_Registry::get(CONFIG)->container->random;?>
<?php if($random && $case == false):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<table class="icontainer" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<span class="verde"><?php echo $this->labels->text->thisentity;?></span>							
		</td>
	</tr>
	<?php if(count($this->assistances) < 1):?>
		<tr>
			<td>
				<?php echo $this->labels->text->noregister;?>							
			</td>
		</tr>		
	<?php endif;?>
	<?php $i = 0;?>
	<?php foreach($this->assistances as $assistance): ?>
		<tr>
			<td>
				<span class="verde">
					<?php if($i < 4):?>
						<?php $description = $assistance[Constants::AST_SUMMARY_DESC]; ?>
							<?php if($assistance[Constants::AST_SUMMARY_TYPE] == Constants::ESPECIAL): ?>
								<?php echo "&loz;&nbsp;".abbreviate($this->controller->attendance->text->especial, 25); ?>	
							<?php elseif($description): ?>
								<?php echo "&loz;&nbsp;".abbreviate($description, 25); ?>	
							<?php else: ?>
								<?php echo "&loz;&nbsp;".abbreviate($this->controller->attendance->text->attendance, 25); ?>					
							<?php endif; ?>		
					<?php else: echo "..."; break;?>
					<?php endif;?>
					<?php $i++; ?>
				</span>
			</td>
		</tr>		
	<?php endforeach;?>
	<tr>
		<td class="alignCenter">
			<input type="submit" onclick="parent.document.location='<?php echo $this->baseUrl;?><?php echo ATTENDANCE_CONTROLLER;?>/<?php echo DEFAULT_ATTENDANCE_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>'" value="<?php echo $this->labels->button->showDetail;?>"/>
		</td>
	</tr>
</table>