<br>
<b><?php echo $this->controller->attendance->text->paraminvalid;?></b>
<p>
<?php printErrorsByField($this->form->classId(), $this->errorMessages);?>
<p>
<a href="<?php echo $this->baseUrl;?><?php echo ATTENDANCE_CONTROLLER;?>/<?php echo GROUP_VIEW_ACTION;?>/<?php echo $this->form->assistanceId();?>/<?php echo $this->form->getAssistanceId();?>">
	<?php echo $this->labels->button->back; ?>
</a>
<p>
