<?php echo $this->render('header/header.phtml');?>										 		  						
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuPerson.phtml');?>

	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	
	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0">
			<?php if($this->errorMessages[$this->form->assistanceId()]):?>
				<tr><td align="center"><?php printErrorsByField($this->form->assistanceId(), $this->errorMessages);?></td></tr>		
			<?php elseif($this->errorMessages[$this->form->personId()]):?>
				<tr><td align="center"><?php printErrorsByField($this->form->personId(), $this->errorMessages);?></td></tr>
			<?php else:?>			
				<tr>
					<td align="center">	
						<?php 
							echo $this->render('attendance/_generalForm.phtml'); // general
						?>					
					</td>
				</tr>
			<?php endif;?>
		</table>
	</div>
</div>																  
<!-- =================================== -->
<!-- fim : específico para cada template -->					
<!-- =================================== -->		
					
<?php echo $this->render('footer/footer.phtml');?>	