<?php $case = false;?>
<?php $show = Zend_Registry::get(CONFIG)->container->identification;?>
<?php if(!$show):?>
	<?php echo $this->render('header/head.phtml');?>
	<?php $case = true;?>
<?php endif;?>
<?php $random = Zend_Registry::get(CONFIG)->container->random;?>
<?php if($random && $case == false):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<table class="icontainer" cellpadding="0" cellspacing="0">
	<tr>
		<td width="30%">
			<span><?php echo $this->controller->person->text->name;?></span>
		</td>
		<td>
			<p>
				<?php 
					if($this->form->getName())
						echo $this->form->getName();
					else
						echo $this->controller->person->text->nodata;
				?>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<span><?php echo $this->controller->person->text->nick;?></span>
		</td>
		<td>
			<p>
				<?php 
					if($this->form->getNickname())
						echo $this->form->getNickname();
					else
						echo $this->controller->person->text->nodata;
				?>
			</p>
		</td>
	</tr>
	<tr>
		<td>
			<span><?php echo $this->controller->person->text->sex;?></span>
		</td>
		<td>
			<p>
				<?php 
					if($this->form->getSex() == Constants::MAN)
						echo $this->controller->person->text->male;
					else if($this->form->getSex() == Constants::WOMAN)
						echo $this->controller->person->text->female;
					else
						echo $this->controller->person->text->nodata;
				?>
			</p>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="alignCenter">
			<input type="submit" onclick="parent.document.location='<?php echo $this->baseUrl;?><?php echo PERSON_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>'" value="<?php echo $this->labels->button->showDetail;?>"/>
		</td>
	</tr>
</table>