<?php echo $this->render('header/headerReport.phtml');?>						 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
<div align="center">	
	
	<table width="570" cellspacing="0" cellpadding="0">
		<tr>
			<td align="left">
			
				<?php if($this->form->getId()):?>
					<h1 class="title" style="margin-top: 33px;">
						<?php echo $this->controller->person->edit->title;?>
					</h1>
				<?php else :?>
					<h1 class="title" style="margin-top: 33px;">
						<?php echo $this->controller->person->add->title;?>
					</h1>
				<?php endif; ?>
				
				<div class="inputBox">
				<table width="548" cellspacing="0" cellpadding="0" style="margin-top: 10px;">
					<?php foreach($this->errorMessages as $k=>$v) if($k == $this->form->id()) $error = true;?>
					<?php if($error === true):?>
							<tr>
								<td>
									<?php printErrorsByField($this->form->id(), $this->errorMessages);?>		
								</td>
							</tr>
					<?php else :?>
						<?php if($this->form->getId()):?>
							<form action="<?php echo $this->baseUrl ?><?php echo PERSON_CONTROLLER;?>/<?php echo DEFAULT_EDIT_ACTION;?>" method="post">
								<input type="hidden" name="<?php echo $this->form->id();?>" value="<?php echo $this->form->getId();?>">
						<?php else :?>
							<form action="<?php echo $this->baseUrl ?><?php echo PERSON_CONTROLLER;?>/<?php echo DEFAULT_ADD_ACTION;?>" method="post">
						<?php endif;?>
					<?php echo $this->render('person/_form.phtml');?>
					<?php endif;?>
			</td>
		</tr>
	</table>
	
	<?php if($this->form->getId()): ?>
		<h1 class="title" style="margin-top: 33px;">
			<?php echo $this->controller->person->edit->tempEditTitle;?>
		</h1>
	<?php else :?>
		<h1 class="title" style="margin-top: 33px;">
			<?php echo $this->controller->person->add->tempAddTitle;?>
		</h1>
	<?php endif; ?>	
	
	<div class="inputBox">
	
		<table width="548" cellspacing="0" cellpadding="0" >
			<tr>
				<td align="center">
					<table width="548" cellspacing="0" cellpadding="0">
						<?php echo $this->render('person/address_temp_form.phtml');?>
					</table>	
				</td>
			</tr>
		</table>
	</div>


	
	<table width="570" cellspacing="0" cellpadding="0">
		<tr>
			<?php if($this->form->getId()):?>
				<td class="left" align="left">
					<?php if($this->readOnly == FALSE):?>
						<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>"/>
					<?php endif; ?>
					<input class="button" type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?><?php echo PERSON_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'">
				</td>
			<?php else :?>
				<td class="left" align="left">
					<?php if($this->readOnly == FALSE):?>
						<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>"/>
					<?php endif; ?>
					<input class="button" type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?><?php echo SEARCH_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'">
				</td>
			<?php endif;?>
		</tr>
		</form>
	</table>
	
</div>	
														  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footerReport.phtml');?>