<input class="button" style="float: left"; type="button" name="name" value="<?php echo $this->labels->button->new; ?>" onclick="show('address_add_form')"/>
<br clear="all" />
<div class="inputBox" id="address_add_form" style="border: none; <?php if(count($this->addressErrorMessages) < 1) echo 'display:none'; ?>">
<input type="hidden" name="<?php echo SearchAddressForm::flgAction();?>" value="<?php echo $this->form->getFlgAction(); ?>"/>

<table style="width:526px; border: 0; padding: 0 !important;" cellpadding="0" cellspacing="0" > 
	<tr>
		<td class="label" width="30%"><?php echo $this->controller->postalcode->text->addresstype;?></td>
		<td colspan="3">
			<input class="small" type="text" name="<?php echo $this->form->adr_addressType();?>" value="<?php echo $this->form->getAdrAddressType();?>">
		</td>
	</tr>
	<tr>
		<td colspan="4">
  			<?php printErrorsByField($this->form->adr_addressType(), $this->addressErrorMessages);?>
		</td>
	</tr>
	<tr>
		<td class="label"><?php echo $this->controller->postalcode->text->address;?>:</td>
		<td colspan="3">
  			<input class="small" type="text" name="<?php echo $this->form->adr_address();?>" value="<?php echo $this->form->getAdrAddress();?>"/>
		</td>
	</tr>
	<tr>
		<td colspan="4">
  			<?php printErrorsByField($this->form->adr_address(), $this->addressErrorMessages);?>
  		</td>
  	</tr>		
	<tr>
		<td class="label"><?php echo $this->controller->postalcode->text->typepostal;?>:</td>
		<td colspan="3">
			<input size="9" maxlength="8" type="text" name="<?php echo $this->form->adr_zipcode();?>" value="<?php echo $this->form->getAdrZipcode();?>">
		</td>
	</tr>
	<tr>
		<td colspan="4">
			<?php printErrorsByField($this->form->adr_zipcode(), $this->addressErrorMessages);?>
		</td>
	</tr>	
	<tr>
		<td width="15%" class="label"><?php echo $this->controller->postalcode->text->neighborhood;?>:</td>
		<td width="25%">
			<input class="small" type="text" name="<?php echo $this->form->adr_neighborhood();?>" value="<?php echo $this->form->getAdrNeighborhood();?>" >
		</td>
		<td width="15%" class="label">&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->controller->postalcode->text->city;?>:</td>
		<td width="20%">
			<input class="small" type="text" name="<?php echo $this->form->adr_city();?>" value="<?php echo $this->form->getAdrCity();?>">
		</td>
	</tr>
	<tr>
		<td colspan="4">
			<?php 
				printErrorsByField($this->form->adr_neighborhood(), $this->addressErrorMessages);
				printErrorsByField($this->form->adr_city(), $this->addressErrorMessages);
			?>
		</td>
	</tr>
	<tr>
		<td class="label"><?php echo $this->controller->postalcode->text->uf;?>:</td>
		<td colspan="3">
			<input type="text" name="<?php echo $this->form->adr_uf();?>" value="<?php echo $this->form->getAdrUf();?>" size="3" maxlength="2" >
		</td>
	</tr>
	<tr>
		<td colspan="4">
			<?php printErrorsByField($this->form->adr_uf(), $this->addressErrorMessages);?>
		</td>
	</tr>
	<tr>
		<td colspan="4" align="left">
			<input class="button" type="submit" name"button" value="<?php echo $this->labels->button->save;?>" 
				onclick="return actionName('<?php echo $this->baseUrl . SEARCHADDRESS_CONTROLLER.'/'.DEFAULT_ADD_ACTION; ?>',this.form);"/>
		</td>
	</tr>
</table>

</div>