<table  width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td align="right">
			<div class="menuFeature">
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo AREA_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->button->admin->entity->expertisearea;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo CLASSIFICATION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->button->admin->entity->classification;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->button->admin->entity->typeprogram;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo ACTIVITY_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->button->admin->entity->activity;?></a>&nbsp;&nbsp;
			</div>																												
		</td>
	<tr>
</table>



