<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center">																												
			&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->profile;?>&nbsp;&nbsp;|</a>
			&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo GROUP_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->group;?></a>&nbsp;&nbsp;
			
		</td>
	<tr>
</table>