<table class="withoutEdge menuPartner" cellpadding="0" cellspacing="0" >
	<tr class="write">
		<td align="right">
			<?php if(ResourcePermission::isAllowResource(ENTITYINITIAL_CONTROLLER)){?>
			<div class="buttonMenu">
				<a href="<?php echo $this->baseUrl. ENTITYINITIAL_CONTROLLER. '/'. DEFAULT_INITIAL_NEW_ACTION;?>">
					<?php echo '+ '. $this->labels->button->preregistration;?>
				</a>
			</div>
			<?php }?>
			<?php if(ResourcePermission::isAllowResource(ASSOCIATE_ENTITY_CONTROLLER)){?>
			<div class="buttonMenu">
				<a href="<?php echo $this->baseUrl. ASSOCIATE_ENTITY_CONTROLLER. '/'. DEFAULT_VIEW_ACTION;?>">
					<?php echo '+ '. $this->labels->button->associate;?>
				</a>
			</div>
			<?php }?>
		</td>
	</tr>
</table>