<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td align="right">
			<div class="menuFeature">
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->region;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->permission;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo ADDITIONALINFORMATION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->additional;?></a>&nbsp;&nbsp;
				&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo IMPORT_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->import;?></a>&nbsp;&nbsp;
			</div>
		</td>
	<tr>
</table>