<tr>
	<td colspan="2">
		<h1 class="title"><?php echo $this->controller->activity->text->newactivity;?></h1>
	</td>
</tr>

<tr>
	<td>
		<div class="inputBox"> 
			<table width="548" cellpadding="0" cellspacing="0" style="margin-top: 10px;">
				<!-- ==================================================== -->
				<!-- formulário que visualiza as informações para edição  -->
				<!-- este formulário é visualizado a partir do view.phtml -->					
				<!-- ==================================================== -->
				<form action="<?php echo $this->baseUrl;?><?php echo ACTIVITY_DETAIL_CONTROLLER;?>/<?php echo DEFAULT_ADD_ACTION;?>" method="post">

					
					<!-- ========================================================================================================== -->
					<!-- =========================================== nome da atividade ============================================ -->
					<!-- ========================================================================================================== -->
					
					<tr>
						<td width="33%" class="label"><?php echo $this->controller->activity->text->name;?>:</td>

						
						
						<td width="67%">
							<input name="<?php echo ActivityForm::nameDetailActivity();?>" type="text" value="<?php echo $this->escape($this->form->getNameDetailActivity());?>"/>
						</td>
					</tr>
					
					<tr>
						<td colspan="2"><?php printErrorsByField($this->form->nameDetailActivity(), $this->errorMessages);?></td>
					</tr>
					
					<!-- ========================================================================================================== -->
					<!-- =========================================== carga horária da atividade =================================== -->
					<!-- ========================================================================================================== -->
					
					<tr>
						<td class="label"><?php echo $this->controller->activity->text->workinghour;?>:</td>
						<td>
							<input name="<?php echo ActivityForm::workingHour();?>" type="text" value="<?php echo $this->escape($this->form->getWorkingHour());?>"/>
						</td>
					</tr>
					
					<tr>
						<td colspan="2"><?php printErrorsByField($this->form->workingHour(), $this->errorMessages);?></td>
					</tr>
					
					<!-- ===================================================================================================== -->
					<!-- =========================================== programa ================================================ -->
					<!-- ===================================================================================================== -->
					<tr>
						<td class="label"><?php echo $this->controller->activity->text->selectProgram;?>:</td>
						<td>
							<select name="<?php echo ActivityForm::idProgram();?>">
								<option value=""><?php echo $this->controller->activity->text->selectProgram;?></option>
								<?php
									foreach($this->programs as $program)
									{	
										$uniqueActivity = $program->findParentRow(CLS_PROGRAMTYPE);
										echo "<option value='";echo $program->{PGR_ID_PROGRAM}."'";
										if($program->{PGR_ID_PROGRAM} == $this->escape($this->form->getIdProgram()))
										{
											echo "selected>"; 	
										}	
										else
										{
											echo ">";	
										}
										echo $uniqueActivity->{PGT_PROGRAM_TYPE}.
										"</option>";
									}
								?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td colspan="2"><?php printErrorsByField($this->form->idProgram(), $this->errorMessages);?></td>
					</tr>
					
					<!-- ====================================================================================================== -->
					<!-- =========================================== atividade ================================================ -->
					<!-- ====================================================================================================== -->
					
					<tr>
						<td class="label"><?php echo $this->controller->activity->text->selectactivity;?>:</td>
						<td>
							<select name="<?php echo ActivityForm::idCategory();?>">
								<option value=""><?php echo $this->controller->activity->text->selectactivity;?></option>
								<?php
									foreach($this->activities as $act)
									{	
										echo "<option value='";echo $act->{CAT_ID_CATEGORY}."'";
										if($act->{CAT_ID_CATEGORY} == $this->escape($this->form->getIdCategory()))
										{
											echo "selected>"; 	
										}	
										else
										{
											echo ">";	
										}
										echo $act->{CAT_CATEGORY}.
										"</option>";
									}
								?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td colspan="2"><?php printErrorsByField($this->form->idCategory(), $this->errorMessages);?></td>
					</tr>
					
					<tr>
						<td colspan="2" align="center">
							<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>"/>
						</td>
					</tr>
					
				</form>
			</table>
		</div>
	</td>
</tr>
