<?php
/*
 * 
 * Created on 19/02/2008 
 * S2it Solutions by Fabricio Meireles Monteiro
 * 
 */
?>
 
<?php echo $this->render('header/header.phtml');?>

<table cellpadding="0" cellspacing="0" width="570">
	<?php 
		if(!$this->errorMessages)
		{
			echo $this->render('program/previewDrop.phtml');
		}
		else
		{
			echo $this->render('program/invalidParam.phtml');
		}
	?>
</table>

<?php echo $this->render('footer/footer.phtml');?>
 

