<?php $case = false;?>
<?php $show = Zend_Registry::get(CONFIG)->container->income;?>
<?php if(!$show):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<?php $random = Zend_Registry::get(CONFIG)->container->random;?>
<?php if($random && $case == false):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<table class="icontainer" cellpadding="0" cellspacing="0">
	<tr>
		<td width="30%">
			<span>
				<?php echo $this->controller->income->title;?>
			</span>
		</td>
	</tr>
	<?php foreach($this->person as $person) $income = $person->findDependentRowset(CLS_INCOME);?>
	<?php if(count($income) > 0):?>
		<?php foreach($income as $inc):?>
			<?php if($inc->{ICM_STATUS} != Constants::HISTORY):?>
				<?php if($inc->{ICM_ID_INCOME} != 1 && $inc->{ICM_VALUE} != 0):?>
					<tr>
						<td>
							<span class="verde">
								<?php $incType = $inc->findParentRow(CLS_INCOMETYPE);?>
								<?php echo '- '.$incType->{ICT_INCOME};?>
							</span>
						</td>
					</tr>								
				<?php endif;?>
			<?php endif;?>
		<?php endforeach;?>
	<?php else:?>
		<tr>
			<td>
				<span class="verde">
					<?php echo '- '.$this->labels->text->nodata;?>
				</span>
			</td>
		</tr>
	<?php endif;?>
	<tr>
		<td class="alignCenter">
			<input type="submit" onclick="parent.document.location='<?php echo $this->baseUrl;?><?php echo INCOME_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>'" value="<?php echo $this->labels->button->showDetail;?>"/>
		</td>
	</tr>
</table>