<?php
/*
 * 
 * Created on 25/02/2008 
 * S2it Solutions by Fabricio Meireles Monteiro
 * 
 */
?>

<tr>
	<td>
		<table class="inputBox"  cellpadding="0" cellspacing="0" style="width: 570px;">
			<tr>
				<td>
					<table width="100%">
						<tr>
							<td colspan="4">
								<h1 class="left;"><?php echo $this->controller->entity->admin->coordinator;?></h1>
							</td>
						</tr>
						<tr>
							<td class="label" width="70"><?php echo $this->controller->entity->text->name;?>:</td>
							<td colspan="3" align="left">
								<input size="80" type="text" maxlength="100" name="<?php echo UserForm::name();?>" value="<?php echo $this->escape($this->userForm->getName());?>"/>
							</td>
						</tr>
						<tr>
							<td colspan="4"><?php printErrorsByField($this->userForm->name(), $this->errorMessages);?></td>
						</tr>
						<tr>
							<td class="label"><?php echo $this->controller->entity->admin->document;?>:</td>
							<td colspan="3" align="left">
								<input size="80" maxlength="11" type="text" name="<?php echo UserForm::cpf();?>" value="<?php echo $this->escape($this->userForm->getCpf());?>"/>
							</td>
						</tr>
						<tr>
							<td colspan="4"><?php printErrorsByField($this->userForm->cpf(), $this->errorMessages);?></td>
						</tr>
						
						<tr>
							<td class="label"><?php echo $this->controller->entity->admin->username;?>:</td>
							<td align="left" width="200">
								<input size="30" type="text" name="<?php echo UserForm::login();?>" value="<?php echo $this->escape($this->userForm->getLogin());?>"/>
							</td>
							<td class="label" align="right" ><span style="margin-left: 10px;"> <?php echo $this->controller->entity->admin->password;?>:</span></td>
							<td align="left" width="200">
								<input size="35" type="password" name="<?php echo UserForm::password();?>" value="<?php echo $this->escape($this->userForm->getPassword());?>"/>
							</td>
						</tr>
						<tr>
							<td colspan="4"><?php 
								printErrorsByField($this->userForm->login(), $this->errorMessages);
								printErrorsByField($this->userForm->password(), $this->errorMessages);
								?>
							</td>
						</tr>
						
						<tr>
							<td class="label" ><?php echo $this->controller->entity->text->email;?>:</td>
							<td colspan="3" align="left">
								<input size="80" type="text" name="<?php echo UserForm::email();?>" value="<?php echo $this->escape($this->userForm->getEmail());?>"/>
							</td>
						</tr>
						<tr>
							<td colspan="4"><?php printErrorsByField($this->userForm->email(), $this->errorMessages);?></td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
		<br />
	</td>
</tr>
