<?php 
	//variável utilizada para setar background do submenu 
	$stringUri = $_SERVER["REQUEST_URI"];
	

?>

<?php if(UserLogged::isManager() || UserLogged::isCoordinator()):?>
<table  width="570" height="" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<div>
				<ul class="submenuCentral adm">
				  <?php if(ResourcePermission::isAllowResource(ENTITY_CONTROLLER)){?>
				  <li style="width:80px;" <?php 
				  		$stringmatch = ENTITY_CONTROLLER; 
			  			if (preg_match("%($stringmatch)%", "$stringUri")){
			  				echo "class='current'";
			  			}?> >
		  				<a href="<?php echo $this->baseUrl;?><?php echo ENTITY_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">
		  				<div class="menuTexto general">
		  					<?php echo $this->labels->title->common;?>
		  				</div>
		  				</a>
		  			</li>
				  <?php }?>
				  
				  <?php if(ResourcePermission::isAllowResource(USER_CONTROLLER)){?>
				  <li style="width:100px;" <?php 
				  	$stringmatch = USER_CONTROLLER; 
				  	if (preg_match("%($stringmatch)%", "$stringUri")){
				  		echo "class='current'";
				  	}?> >
				  	<a href="<?php echo $this->baseUrl;?><?php echo USER_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">
				  		<div class="menuTexto menuUser">
				  			<?php echo $this->labels->title->users;?>
				  		</div>
				  	</a>
				  </li>
				  <?php }?>
				  <?php if(ResourcePermission::isAllowResource(CLASS_CONTROLLER)){?>
				  <li style="width:100px;" <?php 
				  		$stringmatch = CLASS_CONTROLLER; 
				  		if (preg_match("%($stringmatch)%", "$stringUri")){
				  			echo "class='current'";
				  		}?> >
				  		<a href="<?php echo $this->baseUrl;?><?php echo CLASS_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">
				  			<div class="menuTexto group">
				  				<?php echo $this->labels->title->classes;?>
				  			</div>
						</a>
					</li>
				  <?php }?>
				  <?php if(ResourcePermission::isAllowResource(ACTIVITY_DETAIL_CONTROLLER)){?>
				  <li style="width:120px;" class="ultraExtended <?php 
				  		$stringmatch = ACTIVITY_DETAIL_CONTROLLER; 
				  		if (preg_match("%($stringmatch)%", "$stringUri")){
				  			echo "current";
				  	}?>" >
				  		<a href="<?php echo $this->baseUrl;?><?php echo ACTIVITY_DETAIL_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">
							<div class="menuTexto menuActivity">
								<?php echo $this->labels->title->detailActivity;?>
							</div>
						</a>
					</li>
				  <?php }?>
				  <!-- /*RF001 - Adicionar botao monitoramento no sub menu administracao*/ -->
				  <?php
				  /*RF001 - Adicionar botao monitoramento no sub menu administracao*/
				   if(ResourcePermission::isAllowResource(MONITORING_CONTROLLER)){?>
				  <li style="width:150px;"<?php 
				  		$stringmatch = MONITORING_CONTROLLER; 
				  		if (preg_match("%($stringmatch)%", "$stringUri")){
				  			echo "class='current'";
				  		}?>" >
				  		<a href="<?php echo $this->baseUrl;?><?php echo MONITORING_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">
							<div class="menuTexto monitoramento">
								<?php echo $this->labels->title->monitoring;?>
							</div>
						</a>
					</li>
				  <?php }?>
				</ul>
				<font class="fontMenu"></font>
			</div>
		</td>
	</tr>
</table>
<?php endif;?>

