<form action="<?php echo $this->baseUrl;?><?php echo USER_CONTROLLER;?>/<?php echo DEFAULT_CHANGE_PASSWORD_ACTION;?>" method="post">
	
	<h1 class="title"><?php echo $this->controller->user->text->alterPass->password;?></h1> 
	
	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0" style="margin-top: 10px;">
			
			<tr>
				<td class="label" width="30%">
					<?php echo $this->controller->user->text->currentPass->password;?>:
				</td>
				<td>
					<input class="middleInput" maxlength="32" type="password" name="<?php echo $this->form->oldPassword();?>" value="<?php echo $this->form->getOldPassword();?>"/>
				</td>
			</tr>
			
			<tr>
				<td colspan="2"><?php printErrorsByField($this->form->oldPassword(), $this->errorMessages);?></td>
			</tr>
			
			<tr>
				<td class="label">
					<?php echo $this->controller->user->text->newPass->password;?>:
				</td>
				<td>
					<input class="middleInput" maxlength="32" type="password" name="<?php echo $this->form->password();?>" value="<?php echo $this->form->getPassword();?>"/>
				</td>
			</tr>
			
			<tr>
				<td colspan="2"><?php printErrorsByField($this->form->password(), $this->errorMessages);?></td>
			</tr>
			
			<tr>
				<td class="label">
					<?php echo $this->controller->user->text->repeatPass->password;?>:
				</td>
				<td>
					<input class="middleInput" maxlength="32" type="password" name="<?php echo $this->form->repeatPassword();?>" value="<?php echo $this->form->getRepeatPassword();?>"/>
				</td>
			</tr>
			
			<tr>
				<td colspan="2"><?php printErrorsByField($this->form->repeatPassword(), $this->errorMessages);?></td>
			</tr>
		</table>
	</div>
	
	<input class="button" type="button" onClick="history.go(-1)" value="<?php echo $this->labels->button->back;?>"/>
	<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>"/>
</form>