
	<?php if($this->edit === false) {?>
		<h1 class="title"><?php echo $this->controller->fexpense->title->new;?></h1>
	<?php }else{?>
		<h1 class="title"><?php echo $this->controller->fexpense->title->view;?></h1>
	<?php }?>

	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0">
			<?php if(!is_numeric($this->form->getId())){?>
					<tr>
						<td>
							<?php printErrorsByField($this->form->id(), $this->errorMessages);?>		
						</td>
					</tr>
			<?php }else{?>
			<?php if($this->edit === false) {?>
				<form action="<?php echo $this->baseUrl;?><?php echo FAMILYEXPENSE_CONTROLLER;?>/<?php echo DEFAULT_ADD_ACTION;?>" method="post">		
			<?php }else{?>
				<form action="<?php echo $this->baseUrl;?><?php echo FAMILYEXPENSE_CONTROLLER;?>/<?php echo DEFAULT_EDIT_ACTION;?>" method="post">
					<input type="hidden" name="<?php echo $this->form->idExpenseType();?>" value="<?php echo $this->form->getIdExpenseType();?>">
			<?php }?>
				<tr>
					<td colspan="2">
						<?php printErrorsByField($this->form->id(), $this->errorMessages);?>
						<?php printErrorsByField($this->form->idFamily(), $this->errorMessages);?>
					</td>
				</tr>
				
				<tr>
				
					<td width="30%" class="label">
						<?php echo $this->controller->fexpense->text->expenseName;?>:
						<input type="hidden" name="<?php echo $this->form->idFamily();?>" value="<?php echo $this->form->getIdFamily();?>">
						<input type="hidden" name="<?php echo $this->form->id();?>" value="<?php echo $this->form->getId();?>">
					</td>
					
					<td class="middleValign">
						<?php if($this->edit === false) {?>
							<select class="middleInput" name="<?php echo $this->form->idExpenseType();?>">
								<option value=""><?php echo $this->labels->text->select;?>...</option>
								<?php foreach($this->expType as $type):?>						
									<option value="<?php echo $type->{EXT_ID_EXPENSE}?>"
										<?php if($this->form->getIdExpenseType() == $type->{EXT_ID_EXPENSE}) echo 'selected';?>
									>
										<?php echo $type->{EXT_EXPENSE}?> 
									</option>
								<?php endforeach;?>
							</select>
						<?php }else{?>
							<?php $flag = false;?>
							<?php foreach($this->expType as $type):?>
								<?php if($this->form->getIdExpenseType() == $type->{EXT_ID_EXPENSE}) {echo $type->{EXT_EXPENSE}; $flag = true;}?>
							<?php endforeach;?>
							<?php if($flag === false):?>
								<?php echo $this->labels->text->nodata;?>
							<?php endif;?>
						<?php }?>
					</td>
				</tr>
				
				<tr>
					<td colspan="2"><?php printErrorsByField($this->form->idExpenseType(), $this->errorMessages);?></td>
				</tr>
				
				<tr>
					<td class="label">
						<?php echo $this->controller->fexpense->text->value;?>:
					</td>
					<td>
						<input class="smallInput" size="20" type="text" name="<?php echo $this->form->expenseValue();?>" value="<?php echo $this->form->getExpenseValue();?>"/>
					</td>
				</tr>
				
				<tr>
					<td colspan="2"><?php printErrorsByField($this->form->expenseValue(), $this->errorMessages);?></td>
				</tr>
				
				<tr>
					<td colspan="2">
						<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>">
						<input class="button" style="margin-left: 5px;" type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?><?php echo FAMILYEXPENSE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php echo $this->form->id();?>/<?php echo $this->form->getId();?>'"/>
					</td>
				</tr>
			</form>
			<?php }?>
		</table>
	</div>