<?php echo $this->render('header/headerSearch.phtml');?>
<br><br><br>
<table width="570" cellpadding="0" cellspacing="0">
	<tr>
		<td class="alignLeft">
			<?php echo $this->helpcontroller->text4?><b><?php echo $this->helpcontroller->text2?></b>
			<p>
			<?php echo $this->helpcontroller->text5?>
			<p>
			<b class="greenWrite"><?php echo $this->helpcontroller->text6?></b>
		</td>
	</tr> 
</table>
<br><br><br>
<?php echo $this->render('footer/footerSearch.phtml');?>