<?php if($this->errorMessages[$this->form->personId()]):?>
	<?php printErrorsByField($this->form->personId(), $this->errorMessages);?>
<?php else:?>

<table width="100%" cellpadding="0" cellspacing="0">
	<tr><td>	
		<?php if(!is_numeric($this->form->getId())){?>
			<div class="inputBox">
				<table width="548" cellpadding="0" cellspacing="0">
					<tr>
						<td>
							<?php printErrorsByField($this->form->personId(), $this->errorMessages);?>		
						</td>
					</tr>
				</table>
			</div>
			
		<?php }else{?>
			
			<form action="" method="post">
				
				
				<table width="100%" cellpadding="0" cellspacing="0">					
					<tr>
						<td>
							<h1 class="title"><?php echo $this->controller->residence->edit->title;?></h1>
							<input type="hidden" name="<?php echo $this->form->personId();?>" value="<?php echo $this->form->getPersonId();?>"/>
							<input type="hidden" name="<?php echo $this->form->idResidence();?>" value="<?php echo $this->form->getIdResidence();?>"/>
						</td>
					</tr>
				</table>
				
				<div class="inputBox">
				
					<?php echo $this->render('residence/_pre-form.phtml');?>
					
					<?php if(!$this->operator):?>
						<?php echo $this->render('residence/_additional-form.phtml');?>
					<?php endif;?>
				
				</div>
				
				<table width="570" cellpadding="0" cellspacing="0" >
					<tr> 
						<td align="left">
							<?php if($this->readOnly == FALSE):?>
								<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>" onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo RESIDENCE_CONTROLLER;?>/<?php echo DEFAULT_EDIT_ACTION;?>', this.form);"/>
							<?php endif; ?>
							<input class="button" style="margin-left: 5px;" type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?><?php echo RESIDENCE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php echo $this->form->id();?>/<?php echo $this->form->getId();?>'">
						</td>
					</tr>		
				</table>
				
			</form>
			
		<?php }?>
	</td></tr>
</table>
<?php endif;?>