<table width="100%" cellpadding="0" cellspacing="0" style="margin-top: 10px;">	

	<tr>
		<td colspan="5" >
			<?php echo $this->helpcontroller->text3;?>
		</td>
	</tr>
	<tr>
		<td>
			<?php printErrorsByField($this->form->personId(), $this->errorMessages);?>
			<?php printErrorsByField($this->form->idResidence(), $this->errorMessages);?>
			<div id="iframeSearch" style="display: none;">
				<?php echo $this->render(SEARCHADDRESS_CONTROLLER.'/iframe_search.phtml');?>
			</div>
			<div id="buttonIframe" style="display: block;">
				<input class="button" type="button" value="Alterar endereço" onClick="javascript: showDiv('iframeSearch','buttonIframe');"/>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $this->render(SEARCHADDRESS_CONTROLLER.'/_address.phtml');?>
			<?php printErrorsByField($this->form->adr_idAddress(), $this->errorMessages);?>
		</td>
	</tr>
	<tr>
		<td>
			<table width="100%" cellpadding="0" cellspacing="0">
				<tr>
					<td class="label" width="30%" align="right">
						<?php echo $this->controller->residence->text->number;?>:</b>
					</td>
					<td>
						<input class="smallInput" type="text" size="20" name="<?php echo $this->form->adr_number();?>" value="<?php echo $this->form->getAdrNumber();?>">
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php printErrorsByField($this->form->number(), $this->errorMessages);?>					
					</td>
				</tr>	
				<tr>
					<td class="label" align="right">
						<?php echo $this->controller->residence->text->complement;?>
					</td>
					<td>
						<input class="smallInput" size="20" type="text" name="<?php echo $this->form->adr_complement();?>" value="<?php echo $this->form->getAdrComplement();?>"><br>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php printErrorsByField($this->form->complement(), $this->errorMessages);?>
					</td>
				</tr>
				<tr>
					<td class="label" align="right">
						<?php echo $this->controller->residence->text->reference;?>
					</td>
					<td>
						<input size="20" type="text" name="<?php echo $this->form->adr_reference();?>" value="<?php echo $this->form->getAdrReference();?>"><br>
					</td>
				</tr>
				<tr>
					<td colspan="2">
						<?php printErrorsByField($this->form->reference(), $this->errorMessages);?>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>

<table width="100%" cellpadding="0" cellspacing="0">
	
	<tr>
		<td colspan="4">
			<hr>
		</td>
	</tr>
	
	<tr>
		<td colspan="4" class="middleValign">
			<?php echo $this->helpcontroller->text4;?>
		</td>
	</tr>
	
	<tr>
		<td width="12%" class="label">
			<?php echo $this->controller->residence->text->ddd;?>
		</td>
		<td width="21%" class="label">
			<?php echo $this->controller->residence->text->phone;?>
		</td>
		<td></td>
		<td></td>
	</tr>	
	
	<tr>
		<td>	
			<?php foreach($this->form->getDdd() as $ddd):?>
				<div class="inputs">
					<input class="tinyInput" type="text"  name="<?php echo $this->form->ddd();?>[]" value="<?php echo $ddd;?>" size="5px" />
				</div>
			<?php endforeach;?>
		</td>
		<td>
			<?php foreach($this->form->getPhone() as $number):?>
				<div class="inputs">
					<input class="smallInput" type="text" name="<?php echo $this->form->phone();?>[]" value="<?php echo $number;?>" size="15px">
				</div>
			<?php endforeach;?>
		</td>
		<td>
			<table cellpadding="0" cellpadding="0">
			<?php foreach($this->form->getPhoneType() as $type):?>	
			<tr>
				<td height="36">
					<div class="inputs">
						<select class="middleInput" name="<?php echo $this->form->phoneType();?>[]">
							<option value=""><?php echo $this->labels->text->select;?>...</option>
							<?php foreach($this->phoneType as $phoneType):?>
								<option value="<?php echo $phoneType->{TTP_ID_TELEPHONE};?>"
									<?php if($type == $phoneType->{TTP_ID_TELEPHONE}) echo "selected";?>><?php echo $phoneType->{TTP_TELEPHONE};?></option>
							<?php endforeach;?>
						</select>
					</div>
				</td>
			</tr>
			<?php endforeach;?>
			</table>
		</td>
		
		<td>
			<?php foreach($this->form->getIdPhone() as $idPhone):?>
				<?php  if ( $idPhone ) :?>
					<input type="hidden" name="<?php echo $this->form->idPhone();?>[]" value="<?php echo $idPhone;?>">
				<?php  endif;?>
			<?php endforeach;?>
		</td>
	</tr>	
		
	<tr>
		<td>
			
			<?php if(!$this->errorMessages):?>
				<div class="inputs">
					<input class="tinyInput" type="text" name="<?php echo $this->form->ddd();?>[]" value="" size="5px">
				</div>
			<?php endif;?>
		</td>
		<td>
			<?php if(!$this->errorMessages):?>
				<div class="inputs">
					<input class="smallInput" type="text" name="<?php echo $this->form->phone();?>[]" value="" size="15px">
				</div>
			<?php endif;?>
		</td>
		<td class="inputMiddle">
			<?php if(!$this->errorMessages):?>
				<div class="inputs">
					<select class="middleInput"  name="<?php echo $this->form->phoneType();?>[]">
						<option value=""><?php echo $this->labels->text->select;?>...</option>
						<?php foreach($this->phoneType as $phoneType):?>
							<option value="<?php echo $phoneType->{TTP_ID_TELEPHONE};?>"><?php echo $phoneType->{TTP_TELEPHONE};?></option>
						<?php endforeach;?>
					</select>
				</td>
			<?php endif;?>
		</td>
		<td>
			<?php if(!$this->errorMessages):?>
				<input type="hidden" name="<?php echo $this->form->idPhone();?>[]" value=""/>
			<?php endif;?>
		</td>
	</tr>	
	
	<tr>
		<td colspan="4">
			<?php
			if(count($this->errorMessages[$this->form->ddd()]) > 1)
			{
				echo "<span style=\"color: red; font-size: 10pt;\">";
				echo $this->controller->residence->text->ddd.' ';
				echo $this->errorMessages[$this->form->ddd()][0][0];
				echo "</span>\n";
			}
			else
			{
				if($this->errorMessages[$this->form->ddd()])
				{
					echo "<span style=\"color: red; font-size: 10pt;\">";
					echo $this->controller->residence->text->ddd.' ';
					echo "</span>\n";
					printErrorsByField($this->form->ddd(), $this->errorMessages);
				}
			}		

			if(count($this->errorMessages[$this->form->phone()]) > 1)
				{
					echo "<span style=\"color: red; font-size: 10pt;\">";
					echo $this->controller->residence->text->phone.' ';
					echo $this->errorMessages[$this->form->phone()][0][0];
					echo "</span>\n";
				}
				else
				{
					if($this->errorMessages[$this->form->phone()])
					{
						echo "<span style=\"color: red; font-size: 10pt;\">";
						echo $this->controller->residence->text->phone.' ';
						echo "</span>\n";
						printErrorsByField($this->form->phone(), $this->errorMessages);
					}
				}	

				printErrorsByField($this->form->phoneType(), $this->errorMessages);
				printErrorsByField($this->form->idPhone(), $this->errorMessages);
			?>
		</td>
	<tr>
	
	
	<tr>
		<td colspan="4">
			<input class="button" type="submit" value="<?php echo $this->controller->residence->text->savePhone;?>" 
				onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo RESIDENCE_CONTROLLER;?>/<?php echo DEFAULT_TELEPHONE_ACTION;?>', this.form);">
		</td>
	</tr>
	<tr colspan="4">
		<td>&nbsp;</td>
	</tr>
</table>