<?php $case = false;?>
<?php $show = Zend_Registry::get(CONFIG)->container->residence;?>
<?php if(!$show):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<?php $random = Zend_Registry::get(CONFIG)->container->random;?>
<?php if($random && $case == false):?>
	<?php echo $this->render('header/head.phtml');?>
<?php endif;?>
<table class="icontainer" cellpadding="0" cellspacing="0">	
	<?php if($this->address === true):?>
		<tr>
			<td>
				<?php echo $this->controller->residence->text->family;?>
			</td>
		</tr>
	<?php else:?>
		<tr>
			<td width="30%">
				<span><?php echo $this->controller->residence->text->address;?></span>
			</td>
			<td>
				<p>
					<?php 
						if(is_null($this->address)) echo $this->labels->text->nodata;
						else{
							$adrType = $this->address->findParentRow(CLS_ADDRESSTYPE);
							echo abbreviate($adrType->{ADT_DESCRIPTION}.' '.$this->address->{ADR_ADDRESS}, 20);
						}
					?>
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<span><?php echo $this->controller->residence->text->number;?></span>
			</td>
			<td>
				<p>
					<?php
						if($this->form instanceof ResidenceForm)
						{
							if($this->form->getNumber())	
								echo $this->form->getNumber();					
							else
								echo $this->labels->text->nodata;
						}else{
							if($this->numberResidence)	
								echo $this->numberResidence;					
							else
								echo $this->labels->text->nodata;					
						}
					?>
				</p>
			</td>
		</tr>
		<tr>		
			<td>
				<span><?php echo $this->controller->residence->text->neighborhood;?></span>
			</td>
			<td>
				<p>
					<?php 
						if(is_null($this->address)) echo $this->labels->text->nodata;
						else{
							$nbhName = $this->address->findParentRow(CLS_NEIGHBORHOOD);
							echo abbreviate($nbhName->{NHD_NEIGHBORHOOD}, 21);
						}
					?>
				</p>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<span>
				<?php 
					if(!is_null($this->address)){
						$nbhName = $this->address->findParentRow(CLS_NEIGHBORHOOD);
						$city = $nbhName->findParentRow(CLS_CITY);
						$state = $city->findParentRow(CLS_UF);
						echo $city->{CTY_CITY}.' - '.$state->{UF_ABBREVIATION};
					}
				?>
				</span>
			</td>
		</tr>
		<tr>
			<td colspan="2" class="alignCenter">
				<input type="submit" onclick="parent.document.location='<?php echo $this->baseUrl;?><?php echo RESIDENCE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>'" value="<?php echo $this->labels->button->showDetail;?>"/>
			</td>
		</tr>
	<?php endif;?>
</table>