
<h1 class="title"><?php echo ($this->labels->confirm->delete->title);?></h1>

<div class="inputBox">
	<table width="548" cellpadding="0" cellspacing="0" style="margin-top: 10px;">

		<tr>
			<?php if(!$errorMessages && sizeof($errorMessages) <= 0) :?>
			<td width="100%" align="center">
				
				<!-- ==================================================================================================================== -->
				<!-- =================================== FORM utilizado para excluir um relacionamento biológico ======================== -->
				<!-- ==================================================================================================================== -->
				<form action="<?php echo $this->baseUrl;?><?php echo BIOLOGICALRELATIONSHIP_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
					<p>
						<?php echo $this->labels->confirm->delete->text;?>&nbsp;?<br>
						<?php
							echo "<br>".$this->controller->bioRelation->text->relation.":&nbsp;";
							echo "<input type='hidden' name='".$this->form->idPerson()."' value='".$this->form->getIdPerson()."'/>";
							echo "<input type='hidden' name='".$this->form->idParent()."' value='".$this->form->getIdParent()."'/>";
							echo "<b>". $this->form->getPrsName()."</b><br>";
						?>
					</p>
					<div>
						<input class="button" type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->yes;?>" />
						<input class="button" style="margin-left: 5px;" type="button" onClick="document.location='<?php echo $this->baseUrl;?><?php echo BIOLOGICALRELATIONSHIP_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php echo $this->form->idPerson();?>/<?php echo $this->form->getIdPerson();?>'" value="<?php echo $this->labels->confirm->button->cancel;?>" />
					</div>
				</form>	
				<!-- =================================================================================================================== -->
				<!-- ================================================ fim do FORM ====================================================== -->
				<!-- =================================================================================================================== -->		
			</td>
			<?php else:?>
			<td width="100%" align="center">
				<?php printErrorsByField($this->form->idPerson(), $this->errorMessages);?>
				<?php printErrorsByField($this->form->idParent(), $this->errorMessages);?>
				<?php printErrorsByField($this->form->prsName(), $this->errorMessages);?>
			</td>
			<?php endif; ?>
		</tr>
	</table>
</div>
