<?php echo $this->render('header/header.phtml');?>	
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/subMenuRelationship.phtml');?>

	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	
	<h1 class="title"><?php echo $this->controller->bioRelation->search->title;?></h1>
	
	<div class="inputBox">
	<table width="548" cellpadding="0" cellspacing="0">
		<tr>
			<td align="center">
				<table width="100%" cellpadding="0" cellspacing="0">

					
					<tr>
						<td colspan="4" class="middleValign">
							<b><?php echo $this->controller->bioRelation->text->searchPerson;?></b>
						</td>
					</tr>
					
					<tr>
						<td colspan="4">
							<?php echo $this->controller->bioRelation->search->info;?>
						</td>
					</tr>
				</table>
				
				<table width="100%" cellpadding="0" cellspacing="0">
					<?php echo $this->render('biological-relationship/_name_form.phtml'); ?>
				</table>
				
				<table width="100%" cellpadding="0" cellspacing="0">
					<?php echo $this->render('biological-relationship/_document_form.phtml'); ?>
				</table>
				
			</td>
		</tr>
	</table>
	</div>
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>
