<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php
/*
 * Created on 20/03/2008
 * Author: Jefferson
 */

echo $this->render('global.phtml');
header("Content-type: text/html; charset=ISO-8859-1");
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");
?>
<html>
<head>
	<title><?php echo $this->escape($this->labels->app->title);?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/site.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/datepicker/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/datepicker/jquery.ui.datepicker.css" />
	<!--[if IE 7]>
		<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/public/styles/ie7.css" />
	<![endif]-->
	
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/lib.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/select.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/jquery/jquery.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/highcharts/highcharts.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/highcharts/modules/exporting.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/grid_vanguard.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/custom_label.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/ui/home.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/ui/jquery.ui.core.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/ui/jquery.ui.datepicker-pt-BR.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/ui/jquery.ui.datepicker.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/scripts/ui/click_modal.js"></script>
	
	<script type="text/javascript">
		
		function checkAll(field)
		{
			for (i = 0; i < field.length; i++)
				field[i].checked = true ;
		}
		
		function uncheckAll(field)
		{
			for (i = 0; i < field.length; i++)
				field[i].checked = false ;
		}
	
	</script>
	<!-- <script type="text/javascript" src="<?php echo $this->baseUrl;?>/public/jquery/scripts.js"></script> -->	
</head>
