

<?php echo $this->render('header/head.phtml');?>

<body>
	<div class="alignDivCenter"> 
		<table width="970" cellpadding="0" cellspacing="0">
			<tr>
				<td>
					<?php echo $this->render('header/authBar.phtml');?>
					<?php echo $this->render('menu/menu.phtml');?>
					<table width="970" align="center" cellpadding="0" cellspacing="0">
						<tr>						
							<td width="100%" align="center">
							<!-- ============= -->
							<!-- fim do header -->
							<!-- ============= -->