<?php
/*
 * Created on 12/03/2008
 * Author: Jefferson
 */
?>

	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0">
			<tr>
				<td colspan="3">
					<?php printErrorsByField($this->form->idRegion(), $this->errorMessages); ?>
				</td>
			</tr>
			
			<?php $i=0; foreach($this->regions as $region) {?>
				<form name="frm<?php echo $i;?>" method="post">
				<tr>
					<td width="60%">
						<?php echo $region->{RGN_REGION}?>
						<input type="hidden" name="<?php echo RegionForm::idRegion();?>" value="<?php echo $region->{RGN_ID_REGION};?>">
					</td>
					<td width="15%">				
						<a href="javascript: document.frm<?php echo $i;?>.action='<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_VIEW_ACTION;?>'; document.frm<?php echo $i;?>.submit();">
							<?php echo $this->labels->button->edit;?>
						</a>
					</td>
					<td width="15%">				
						<a href="javascript: document.frm<?php echo $i;?>.action='<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_CONFIRM_ACTION;?>'; document.frm<?php echo $i;?>.submit();">
							<?php echo $this->labels->button->drop;?>
						</a>
					</td>
				</tr>
				</form>
			<?php $i++;  }?>
		</table>
	</div>
