<?php echo $this->render('header/header.phtml');?>										 		  						
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuAdm.phtml');?>

	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
		
	
		<table width="570" cellpadding="0" cellspacing="0">
			<tr>
				<td align="center">
					<?php echo $this->render('navigation/navigationSetup.phtml');?>
				</td>
			</tr>
		</table>
		
		<table width="100%" cellpadding="0" cellspacing="0">
		
			<tr>
				<td><h1 class="title" style="margin-top:33px;"><?php echo $this->controller->region->title->listRegion;?></h1></td>
			</tr>
			
			<tr>
				<td>
					<div class="menuEdit">
						<div class="buttonGreen new">
							<a href="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_NEW_ACTION;?>"><?php echo $this->controller->region->button->newRegion;?></a>
						</div>
					</div>
				</td>
			</tr>
		</table>
		
		
		<table width="570" cellpadding="0" cellspacing="0">
			<tr>
				<td align="center">
					<?php echo $this->render('region/_indexForm.phtml');?>
				</td>
			</tr>
		</table>
	
</div>																  
<!-- =================================== -->
<!-- fim : específico para cada template -->					
<!-- =================================== -->		
					
<?php echo $this->render('footer/footer.phtml');?>	