<table width="548" cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="4"><h1 class="title"><?php echo $this->controller->search->text->bydocument;?></h1></td>
	</tr>
	<tr>
		<td colspan="4"><?php echo $this->helpcontroller->text1;?><br><br></td>
	</tr>
	
	<form action="<?php echo $this->baseUrl;?><?php echo SEARCH_CONTROLLER;?>/<?php echo DEFAULT_SEARCH_BY_DOCUMENT_ACTION;?>" method="post">
	<tr>
		<td class="label" width="12%" >
			<?php echo $this->controller->search->text->number;?>
		</td>
		
		<td width="35%">
			<input type="text" name="<?php echo $this->form->docNumber();?>" value=""/>
		</td>
		
		<td class="label" width="20%">
			<span style="margin-left: 15px;"><?php echo $this->controller->search->text->document;?></span>
		</td>
		
		<td width="38%">
			<select name="<?php echo $this->form->docType();?>">
				<?php foreach($this->documentOptions as $k=>$v):?>
					<option value="<?php echo $k;?>"><?php echo $v;?></option>
				<?php endforeach;?>
			</select>
			<?php ?>
		</td>
	</tr>
	
	<tr>
		<td colspan="4" class="adjustHeight">
			<div>
				<?php 
					printErrorsByField($this->form->docNumber(), $this->errorMessages);
					printErrorsByField($this->form->docType(), $this->errorMessages);
				?>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="4" >
			<input class="button" type="submit" value="<?php echo $this->controller->search->button->search;?>"/><br><br>
		</td>
	</tr>
	</form>
	<tr>
		<td colspan="4">&loz;&nbsp;<?php echo $this->helpcontroller->text2;?></td>
	</tr>
</table>