<?php echo $this->render('header/headerClass.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0" >
			<?php 
				if(!$this->errorMessages)
				{
					echo $this->render('success/_success.phtml');
				}
				else
				{	
					echo $this->render('class/invalidParam.phtml');
				}
			?>
		</table>
	</div>
	
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footerSearch.phtml');?>