	
	<tr>
		<td><h1 class="title"><?php echo $this->controller->classtemplate->text->newclass;?></h1></td>
	</tr>	

	<tr><td>
	<div class="inputBox">
		<table width="548" cellpadding="0" cellspacing="0" style="margin-top: 10px;" >
			<!-- ==================================================== -->
			<!-- formulário que visualiza as informações para edição  -->
			<!-- este formulário é visualizado a partir do view.phtml -->					
			<!-- ==================================================== -->
			<?php printErrorsByField($this->form->idEntity(), $this->errorMessages);?>
			<form id="classForm" action="<?php echo $this->baseUrl;?><?php echo CLASS_CONTROLLER;?>/<?php echo DEFAULT_EDIT_ACTION;?>" method="post">
				<?php if(sizeof($this->programs) > 0 ):?>
					
					<?php			
						if($this->errorMessages[$this->form->idProgram()])
						{
							$existActivityAssociated = true;
						}
						else
						{
							foreach($this->activities as $activity)
							{
								$aad = $activity->findDependentRowset(CLS_ACTIVITYDETAIL);
								foreach($aad as $act)
								{
									$existActivityAssociated = true;
									break;
								}	
							}
						}
					?>
				
					<?php if($existActivityAssociated):?>
						<input type="hidden" name="<?php echo ClassForm::idEntity();?>" value="<?php echo $this->escape($this->form->getIdEntity());?>"/>
						<input type="hidden" name="<?php echo ClassForm::idClass();?>" value="<?php echo $this->escape($this->form->getIdClass());?>"/>

						<?php
							if($this->classes && sizeof($this->classes->findDependentRowset(CLS_ACTIVITYCLASS)) > 0)
							{
								$activities = $this->classes->findDependentRowset(CLS_ACTIVITYCLASS);
								if($activities != null)
								{	
									foreach($this->classes->findDependentRowset(CLS_ACTIVITYCLASS) as $aac)
									{	
										$idActivity = array();
										
										if(!$aac->{ACC_END_DATE})
										{
											$idActivity = $aac->{ACC_ID_ACTIVITY_DETAIL};
											$collActivity[] = $idActivity;
											
											$i = 0;
											if($i == 0)
											{	
												$existIdActivity = TRUE;
												$i++;
											}
										}
									}
								}
							}
						?>
						<tr>
							<td class="label" width="17%">
								<?php echo $this->controller->classtemplate->text->program;?>:
							</td>
							
							<td>
								<select name="<?php echo ClassForm::idProgram();?>" onchange="javascript: submitForm('<?php echo $this->baseUrl;?><?php echo CLASS_CONTROLLER;?>/<?php echo DEFAULT_LOAD_PROGRAM_BY_CLASS;?>','classForm');">
									<?php
										foreach($this->programs as $program)
										{	
											if($program->{PGR_ID_PROGRAM} == $this->classes->{CLS_ID_PROGRAM})
											{	
												$uniqueActivity = $program->findParentRow(CLS_PROGRAMTYPE);
												echo "<option value='";echo $program->{PGR_ID_PROGRAM}."'";
												echo " selected>";
												echo $program->findParentRow(CLS_PROGRAMTYPE)->{PGT_PROGRAM_TYPE};
												echo "</option>";	
											}
										}
									?>
								</select>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->idProgram(), $this->errorMessages);?></td>
						</tr>
						
						<?php if($this->flagEdit):?>
							<script language="JavaScript" type="text/javascript">
								submitForm('<?php echo $this->baseUrl;?><?php echo CLASS_CONTROLLER;?>/<?php echo DEFAULT_LOAD_PROGRAM_BY_CLASS;?>','classForm');
							</script>
						<?php endif;?>
						
						<tr>
							<td class="label">
								<?php echo $this->controller->classtemplate->text->activity;?>:
							</td>
							
							<td>
								<!-- =================================== verifica se "idActivityDetail" foi carregado ======================================== --> 
								<input type="hidden" name="<?php echo ClassForm::existActDetail();?>" value="<?php echo $existIdActivity; ?>"/>
								<!-- ========================================================================================================================= -->
								
								<?php if($this->activities && sizeof($this->activities) > 0 ):?>
								<select name="<?php echo ClassForm::idActivityDetail();?>[]" multiple>
									<?php
										foreach($this->activities as $activity)
										{	
											$aad = $activity->findDependentRowset(CLS_ACTIVITYDETAIL);
											foreach($aad as $act)
											{	
												if(!(in_array($act->{ACD_ID_ACTIVITY_DETAIL}, $collActivity)))
												{
													echo "<option value='";echo $act->{ACD_ID_ACTIVITY_DETAIL}."'";
													if(sizeof($this->form->getIdActivityDetail()) > 0)
													{
														if(in_array($act->{ACD_ID_ACTIVITY_DETAIL},$this->form->getIdActivityDetail())){
															echo "selected>";	
														}
														else
														{
															echo ">";	
														}
													}	
													else
													{
														echo ">";	
													}		
													echo $uniqueActivity = $act->findParentRow(CLS_CATEGORY)->{CAT_CATEGORY}.' - '.
													$act->{ACD_ACTIVITY_DETAIL}.
													"</option>";
												}							
											}
										}
									?>
								</select>
								<?php else:?>
									<?php echo $this->controller->classtemplate->text->noActivity;?>
								<?php endif;?>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->idActivityDetail(), $this->errorMessages);?></td>
						</tr>
						
						<?php 
							echo "<tr>";
							echo "<td>&nbsp;</td>";
							echo "<td class='middleValign'><b>";
							echo $this->controller->classtemplate->text->activityRegistered;
							echo ":</b></td>";
							echo "</tr>";
							
							echo "<tr>";
							echo "<td>&nbsp;</td>";
							echo "<td>";
						?>				
						<?php if($this->activities && sizeof($this->activities) > 0 ):?>
							<?php
							$iterator = 0;				
							if($this->classes)
							{
								foreach($this->classes->findDependentRowset(CLS_ACTIVITYCLASS) as $activities)
								{	
									if(!$activities->{ACC_END_DATE})
									{	
										foreach($this->activities as $activity)
										{
											$aad = $activity->findDependentRowset(CLS_ACTIVITYDETAIL);
											foreach($aad as $act)
											{
												if(in_array($act->{ACD_ID_ACTIVITY_DETAIL}, $collActivity))
												{
													if($activities->{ACC_ID_ACTIVITY_DETAIL} == $act->{ACD_ID_ACTIVITY_DETAIL})
													{	
														echo "<div class='alert'>";
														echo "<table width='100%' cellpadding='0' cellspacing='0'>";
															echo "<tr>";
																
																echo "<td width='50%'>";
																echo "<b>";
																echo $act->findParentRow(CLS_CATEGORY)->{CAT_CATEGORY}.' - '.$act->{ACD_ACTIVITY_DETAIL};
																echo "</b>";
																echo "</td>";	
															
																echo "<td width='50%'>";
																echo "<a href='";echo $this->baseUrl;echo CLASS_CONTROLLER;
																echo "/"; 
																echo DEFAULT_CLOSE_ACTIVITY_ACTION; 
																echo "/"; 
																echo ClassForm::idActivityClass();
																echo "/";
																echo $activities->{ACC_ID_ACTIVITY_CLASS};
																echo "'>";
																echo $this->controller->classtemplate->text->closeactivity;
																echo"</a>";
																echo "</td>";
															
															echo "</tr>";
														echo "</table>";
														echo "</div>";
														$iterator ++;
													}
												}
											}
										}
									}
								}
							}
							if($iterator == 0)
							{
								echo "<b class='writeRed'>Não há atividades para essa turma.</b>";
							}
							echo "</td>";
							echo "</tr>";
							echo "<tr><td height='10'></td></tr>";
							?>
						<?php endif;?>
						
						<tr>
							<td class="label">
								<?php echo $this->controller->classtemplate->text->name;?>:
							</td>
							
							<td>
								<input type="text" name="<?php echo ClassForm::className();?>" value="<?php if($this->escape($this->form->getClassName())) echo $this->escape($this->form->getClassName()); else echo $this->classes->{CLS_NAME}?>"/>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->className(), $this->errorMessages);?></td>
						</tr>
						
						<tr>
							<td class="label">
								<?php echo $this->controller->classtemplate->text->vacancies;?>:
							</td>
							
							<td>
								<input class="middleInput" type="text" name="<?php echo ClassForm::vacancy();?>" value="<?php if($this->escape($this->form->getVacancy())) echo $this->escape($this->form->getVacancy()); else echo $this->classes->{CLS_VACANCY}?>"/>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->vacancy(), $this->errorMessages);?></td>
						</tr>
						
						<tr>
							<td class="label">
								<?php echo $this->controller->classtemplate->text->period;?>:
							</td>
							<td>
								<select class="smallInput" name="<?php echo ClassForm::period();?>">
									<?php 
										if($this->escape($this->form->getPeriod()))
										{
											$selected = $this->escape($this->form->getPeriod());
										}
										else
										{
											$selected = $this->classes->{CLS_PERIOD};
										}
									?>
									<?php foreach($this->allPeriod as $k => $value): ?>
										<option value="<?php echo $k; ?>" <?php if($selected == $k ) echo selected;?>><?php echo $value; ?></option>
									<?php endforeach; ?>
								</select>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->period(), $this->errorMessages);?></td>
						</tr>
						
						<tr>
							<td class="label">
								<?php echo $this->controller->classtemplate->text->time;?>:
							</td>
							<td>
								<input class="smallInput" type="text" name="<?php echo ClassForm::timeClass();?>" value="<?php if($this->escape($this->form->getTimeClass())) echo $this->escape($this->form->getTimeClass()); else echo $this->classes->{CLS_SCHEDULE}?>"/>
							</td>
						</tr>
						
						<tr>
							<td colspan="2"><?php printErrorsByField($this->form->timeClass(), $this->errorMessages);?></td>
						</tr>
						
						<tr>
							<td colspan="2" align="center">
								<input class="button" type="submit" value="<?php echo $this->controller->classtemplate->button->edit;?>"/>
							</td>
						</tr>
						
						<?php else:?>
							<tr>
								<td colspan="2" class="middleValign">
									<b><?php echo $this->helpcontroller->text5?></b>
								</td>
							</tr>
							
							<tr>
								<td colspan="2" class="middleValign">
									<b><?php echo $this->helpcontroller->text4?></b>
								</td>
							</tr>
							
						<?php endif;?>
					<?php else :?>
					
						<tr>
							<td colspan="2" class="middleValign">
								<b><?php echo $this->helpcontroller->text3?></b>
							</td>
						</tr>
						
						<tr>
							<td colspan="2" class="middleValign">
								<b><?php echo $this->helpcontroller->text1?></b>
							</td>
						</tr>
						
						<tr>
							<td colspan="2" class="middleValign">
								<b><?php echo $this->helpcontroller->text4?></b>
							</td>
						</tr>
						
					<?php endif ;?>
			</form>
		</table>
	</div>
	</tr></td>
