<?php echo $this->render('header/headerClass.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	<h1 class="title"><?php echo $this->controller->classtemplate->text->editClass;?></h1>
	<table width="570" cellpadding="0" cellspacing="0" >
		<?php echo $this->render('class/edit_form.phtml');?>
	</table>

	
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		
<br>
<?php echo $this->render('footer/footerSearch.phtml');?>