<?php
/*
 * 
 * Created on 19/02/2008 
 * S2it Solutions by Fabricio Meireles Monteiro
 * 
 */
?>
 
<?php echo $this->render('header/header.phtml');?>
<?php echo $this->render('submenu/submenuAdm.phtml');?>

<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	
	<h1 class="title">
		<?php echo ($this->labels->confirm->disable->title);?>
	</h1>	
	
	<form action="<?php echo $this->baseUrl;?><?php echo ACTIVITY_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
		<table class="inputBox" cellpadding="0" cellspacing="0" style="width: 570px;">

			<tr>
				<td class="middleValign" width="15%" align="right">
					<img src="<?php echo $this->baseUrl;?>/public/styles/alert.jpg"/>
				</td>
				<td width="85%" align="center">
					<?php printErrorsByField($this->form->idActivity(), $this->errorMessages);?>
					
						<p style="margin-top: 10px">
							<?php echo $this->labels->confirm->disable->text;?>
							<?php 
							foreach($this->macroActivities as $macro)
							{
								echo '<br>'. $macro->{CAT_ID_CATEGORY} .' - ';
								echo $macro->{CAT_CATEGORY}.'<br>';
							}
							?>
						</p>				
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<div>
							<?php foreach($this->macroActivities as $macro) {?>
								<input class="button" style="margin-right: 5px; width: 138px; padding: 0" type="hidden" name="<?php echo $this->form->idActivity();?>[]" value="<?php echo $macro->{CAT_ID_CATEGORY};?>" />
							<?php } /*end foreach*/ ?>
							<input class="button" type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->yes;?>" />
							<input class="button" style="margin-left: 5px" type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->cancel;?>" 
							onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo ACTIVITY_CONTROLLER;?>/<?php echo DEFAULT_NEW_ACTION;?>',this.form);"/>
						</div>
				</td>
			</tr>
			<tr>
				<td><br /> </td>
			</tr>
		</table>
	</form>		

<?php echo $this->render('footer/footer.phtml');?>
 

