<?php echo $this->render('header/header.phtml');?>

<div>
	<?php echo $this->render('submenu/subMenuRelationship.phtml');?>
	
	
		<table width="570" cellpadding="0" cellspacing="0">
			<?php 
				if(!$this->errorMessages)
				{
					echo $this->render('family-relationship/previewDrop.phtml');
				}
				else
				{
					echo $this->render('family-relationship/invalidParam.phtml');
				}
			?>
		</table>

</div>

<?php echo $this->render('footer/footer.phtml');?>
 

