<?php echo $this->render('header/header.phtml');?>	
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/subMenuRelationship.phtml');?>

	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	
	<h1 class="title"><?php echo $this->controller->fRelationship->search->title;?></h1>
	
	<div class="inputBox">
	<table width="548" cellpadding="0" cellspacing="0">
		<tr>
			<td align="center">
				
				<table width="100%" cellpadding="0" cellspacing="0">			
					<tr>
						<td colspan="4" class="middleValign">
							<b><?php echo $this->controller->fRelationship->text->searchPerson;?></b>
						</td>
					</tr>
					
					<tr>
						<td colspan="4">
							<b><?php echo $this->controller->fRelationship->text->info;?></b>
						</td>
					</tr>
					
					<tr>
						<td colspan="4" class="middleValign">
							<b><?php echo $this->controller->fRelationship->search->info;?></b>
						</td>
					</tr>
					
					
					<tr>
						<td colspan="4">
							<table width="100%" cellpadding="0" cellspacing="0">
								<tr>
									<td class="middleValign" width="100%">
										<b><?php echo $this->controller->fRelationship->text->isRepresentative;?></b>
										<br />
  										<input class="button" type="button" onclick="javascript: show('kinship'); hide('formSearch')" value="<?php echo $this->controller->fRelationship->button->isRepresentative;?>"/>
									</td>
								</tr>
								<tr>
									<td>
										<?php printErrorsByField($this->form->idPerson(),$this->errorMessages);?>
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
				
				<!-- =============================== -->
				<!-- possíveis graus de parentesco   -->
				<!-- =============================== -->
				<div id="kinship" style="display: none;">
					<form action="<?php echo $this->baseUrl;?><?php echo FAMILYRELATIONSHIP_CONTROLLER;?>/<?php echo DEFAULT_IS_REPRESENTATIVE_ACTION;?>" method="post">
						<input type="hidden" name="<?php echo SearchForm::idPerson();?>" value="<?php echo $this->form->getIdPerson();?>"/>
						<div class="featuredBlue">
							<table width="100%" cellpadding="0" cellspacing="0">
								<tr>
									<td width="55%" class="middleValign">
										<?php 
											echo $this->controller->fRelationship->representative->role;
											echo "<b><u>".$this->controller->fRelationship->text->representative.":</u></b>";
										?>
									</td>
									<td width="45%" class="middleValign">
										<select class="middleInput" name="<?php echo SearchForm::idkinship();?>">
											<option value=""><?php echo $this->labels->text->select;?>...</option>
											<?php 
												foreach($this->kinship as $kinship)
												{
													echo "<option value='";
													echo $kinship->{KST_ID_KINSHIP};
													echo "'>";
													echo $kinship->{KST_KINSHIP};
													echo "</option>";		
												}
											?>
										</select>
									</td>
								</tr>
							</table>
						</div>
						<input class="button" type="submit" value="<?php echo $this->labels->button->save;?>" />
					</form>
				</div>
				<!-- =============================== -->
				<!-- possíveis graus de parentesco   -->
				<!-- =============================== -->

				<div id="formSearch" style="display: inline;">
					<table width="100%" cellpadding="0" cellspacing="0">
						<tr>
							<td>
							
								<table width="100%" cellpadding="0" cellspacing="0">
									<?php echo $this->render('family-relationship/_name_form.phtml'); ?>
								</table>
								
								<table width="100%" cellpadding="0" cellspacing="0">
									<?php echo $this->render('family-relationship/_document_form.phtml'); ?>
								</table>
							</td>
						</tr>
					</table>
				</div>
			</td>
		</tr>
	</table>
	</div>
	
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>
