<?php 
	//variável utilizada para setar background do submenu 
	$stringUri = $_SERVER["REQUEST_URI"];
	
	$controllerReport = REPORT_CONTROLLER;
	
	if(preg_match("%($controllerReport)%", "$stringUri"))
	{
		$setAdministrator = TRUE;
	}
	$config = Zend_Registry::get(CONFIG);
?>
		
<table class="withoutEdge"
	<?php 
		if($setAdministrator === TRUE)
		{
			echo "width='970'";
		}
		else
		{
			echo "width='570'";
		}
	?>
	cellpadding="0" cellspacing="0" align="center">
	
	
	<tr>
		<?php 
			if($setAdministrator === TRUE)
			{
				echo "<td width='970' align='center'>";
			}
			else
			{
				echo "<td width='970' align='center'>";
			}
		?>
				<div class="rodape">
					<div class="titulo">
						<?php if(!empty($config->link->text)):?>
							<a target='_blank' href='<?php echo $config->link->text;?>'>
								<?php echo $config->name->text;?>
							</a>
						<?php else:?>
							<?php echo $config->name->text;?>
						<?php endif;?>
					
						<?php echo $config->phone->text .$config->phone->number;?>
					
					</div>
					
					<div class="versao">
						<?php echo $config->version->version." <span class='verde'>".$config->version->number."</span>";?>
					</div>
				</div>
			</td>
		</tr>
</table>