<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuAdm.phtml');?>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
</div>
<div style="text-align: left; margin-top:15px; font-size:16px;">
	<h3>Escolha apenas um dos filtros abaixo:</h3><br />
	<form name="opcoes" id="opcoes" action="<?php echo $this->baseUrl;?><?php echo MONITORING_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>" method="post">
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op1 ?>" /> <?php echo $this->controller->monitoring->text->op1 ?><br />
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op2 ?>" /> <?php echo $this->controller->monitoring->text->op2 ?><br />
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op3 ?>" /> <?php echo $this->controller->monitoring->text->op3 ?><br />
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op4 ?>" /> <?php echo $this->controller->monitoring->text->op4 ?><br />
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op5 ?>" /> <?php echo $this->controller->monitoring->text->op5 ?><br />
		<input type="radio" name="op" value="<?php echo $this->controller->monitoring->value->op6 ?>" /> <?php echo $this->controller->monitoring->text->op6 ?><br />
		<?php if($this->msg){ ?>		
			<div class="error" style="font-size:12px;">
				<span>
					<?php echo $this->msg ?>
					<br/>
				</span>	
			</div>
		<?php } ?>
		<br/>
		<input class="button" type="submit" value="Aplicar filtro selecionado"/>
	</form>
</div>

												  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		
<?php echo $this->render('footer/footer.phtml');?>