
<div class="inputBox" style="margin-bottom: 5px;">
<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td class="bold" style="text-align: center; line-height: 30px;">
			<div class="success">
				<img style="float: left;" src="<?php echo $this->baseUrl;?>/public/images/logado.png"/>
				<span style="float: left;">
					<?php echo $this->escape($this->labels->success->title);?>
				</span>
			</div>
		</td>
		
	</tr>
</table>
</div>